# Generated by Django 6.0.4 on 2026-05-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_is_published_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={},
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="inn",
            field=models.CharField(max_length=50),
        ),
    ]
